language: node_js
node_js:
  - "node"

git:
  depth: 3

branches:
  only:
  - master
  - v2

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - set -e
  - ./scripts/clean.sh

script:
  - yarn run lint
  - yarn run test:js
  - source ./scripts/installAndroidSDK.sh
  - yarn run test:android

after_script:
  - echo "BUILD FINISHED"
