language: java

jdk:
  - oraclejdk8

env:
  global:
    - NODE_VERSION=stable
    - ANDROID_HOME=$HOME/android-sdk-linux
    - PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

git:
  depth: 3

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native/
    - $HOME/.gradle/daemon/
    - $HOME/.gradle/caches/
    - $HOME/.m2
    - $ANDROID_HOME/licenses/

before_cache:
  - rm -rf $HOME/.gradle/caches/modules-2
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

before_install:
  - set -e
  - ./scripts/clean.sh

install:
  - nvm install $NODE_VERSION
  - npm i -g yarn
  - yarn

script:
  - yarn run lint
  - yarn run test:js
  - ./scripts/installAndroidSDK.sh
  - yarn run test:android

after_script:
  - echo "BUILD FINISHED"
